### ISSUE TITLE
Refactor: User can search for exercise

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/fitness-logger#23]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Create a new branch and remove the existing code
- [x] Open the old code and reference it when needed
- [x] Import the fonts - work sans and merriweather
- [x] Create the logo Fitness Log with a fontawesome icon
- [x] Import a search icon from fontawesome
- [x] Create form element for submitting a search
- [x] Create the select, dropdown option form element
- [x] Create the submit button
- [x] Get the form element from DOM
- [x] Listen for submit events on the form element
- [x] When the event occurs get the dropdown input form element text
- [x] Make fetch request to the wger API with input text and the right headers
- [x] Store the exercise data retrieved from the API in an array of objects
- [x] Parse the paragraph text in a way that makes it clean and uniform
- [x] Create a DOM element creator function
- [x] Create a workout item creator function
- [x] Loop through the data from the database and make workout items
- [x] Add each workout item to the page with its index as an id
- [x] Listen for user clicks on workout items
- [x] Turn the border green when the user clicks a workout item and if it already has a green border, remove the border
- [x] Add the id of the workout item to an array that keeps track of saved workouts
- [x] On page swap use the list of saved workouts to add them to a global data object
- [x] Store the data object in local storage upon page reload
- [x] Retrieve the data object from local storage upon page reload
