### ISSUE TITLE
Refactor: User can view saved exercises

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/fitness-logger#24]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

Upon page load, the home page should show the exercises coming up in order of soonest to latest
- [x] Create a function called buildHomepage
- [x] Go through each exercise in the data object
- [x] For each day of exercises, call the buildUl function and give it the exercise data object
- [x] Create a function called buildDaySeparator
- [x] For each day of exercises, call the buildDaySeparator and have that function construct a day separator like the figma
- [x] Insert the day separator element at the start of the Ul as a child
- [x] Create a div with a class of home after the div with a class of search
- [x] Modify buildUl to receive the Ul element to append to
- [x] Provide logic to check if there is already a Ul made for that day
- [x] If so, createLi elements for the new workouts
- [x] Append the new lis to the Ul for that day
- [x] If not, createUl with lis and day separator
