### ISSUE TITLE
Refactor: 

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/fitness-logger#25]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] Make 2 views for the create page, new and saved
- [ ] Under the new view, show a form that takes in the inputs necessary to make a new post
- [ ] Have a submit and a reset button
- [ ] When submit is clicked, save the new workout under the nextexerciseId with the number a at the start
